volumes:
  nexus_data:

networks:
  prodnetwork:
    driver: bridge

services:
  nexus:
    hostname: nexus
    container_name: nexus
    image: sonatype/nexus3:3.76.1-java17-ubi
    #image: sonatype/nexus3
    ports:
      - "32510:8081"
      - "30999:30999"
    volumes:
      - nexus_data:/nexus-data
    networks:
      - prodnetwork